# MAAI Configuration File
# Defines settings for the agents and orchestrator.

llm:
  # The model name to use for all agents (e.g., 'gemini-2.5-pro-preview-03-25')
  model_name: 'gemini-2.5-pro-preview-03-25'

# Add other configurations below as needed
# e.g., agent-specific settings, temperature, max_retries, etc.